replicaCount: 1
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101
  seccompProfile:
    type: RuntimeDefault

imagePullSecrets:
  - name: huytruong

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

probes:
  liveness:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 3
  readiness:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

ingress:
  className: nginx
  tls: [{ host: 'ui.kfm.vn', secretName: 'kingfoodmart-com' }]
  hosts: [
    {
      host: 'ui.kfm.vn',
      paths: [{ path: '/', pathType: Prefix, servicePort: 80 }]
    }
  ]
