import type { Project } from "@/types"

export const PROJECTS: Project[] = [
  // t1
  { id: "p1", name: "Auth System Overhaul",   emoji: "🔐", identifier: "AUTH", description: "Rebuild authentication: OAuth2, SAML SSO, 2FA, session management.",                  status: "active",   progress: 62, ownerId: "u1", ownerName: "Alex Nguyen",       tenantId: "t1", issueCount: 5, startDate: "2025-04-01", targetDate: "2025-05-31", createdAt: "2025-03-28" },
  { id: "p2", name: "Developer Portal v2",    emoji: "📖", identifier: "DEV",  description: "New API docs site with OpenAPI explorer, sandbox, and changelog.",                   status: "active",   progress: 35, ownerId: "u2", ownerName: "Sarah Chen",        tenantId: "t1", issueCount: 3, startDate: "2025-04-15", targetDate: "2025-06-30", createdAt: "2025-04-10" },
  { id: "p3", name: "Mobile App Beta",        emoji: "📱", identifier: "MOB",  description: "iOS and Android beta release targeting field operations teams.",                     status: "planning", progress: 5,  ownerId: "u3", ownerName: "John Doe",          tenantId: "t1", issueCount: 2, targetDate: "2025-08-01",                          createdAt: "2025-04-25" },
  // t2
  { id: "p4", name: "Kanban + Time Tracking", emoji: "🗂️", identifier: "KAN",  description: "Visual Kanban board with drag-and-drop and built-in time logging per issue.",        status: "active",   progress: 48, ownerId: "u10", ownerName: "Priya Patel",      tenantId: "t2", issueCount: 4, startDate: "2025-04-05", targetDate: "2025-06-15", createdAt: "2025-04-01" },
  { id: "p5", name: "Integrations Hub",       emoji: "🔌", identifier: "INT",  description: "Slack, email digest, and webhook integrations. One unified settings page.",          status: "active",   progress: 71, ownerId: "u11", ownerName: "Carlos Ruiz",      tenantId: "t2", issueCount: 3, startDate: "2025-03-20", targetDate: "2025-05-20", createdAt: "2025-03-15" },
  { id: "p6", name: "Guest Access",           emoji: "👥", identifier: "GST",  description: "Read-only guest roles for external stakeholders. No billing exposure.",              status: "planning", progress: 10, ownerId: "u12", ownerName: "Yuki Tanaka",      tenantId: "t2", issueCount: 1, targetDate: "2025-07-01",                          createdAt: "2025-04-20" },
  // t3
  { id: "p7", name: "Offline-First PWA",      emoji: "📡", identifier: "PWA",  description: "Service Worker + IndexedDB cache layer. Full CRUD while offline, background sync.", status: "active",   progress: 40, ownerId: "u16", ownerName: "Omar Hassan",      tenantId: "t3", issueCount: 4, startDate: "2025-04-10", targetDate: "2025-06-30", createdAt: "2025-04-08" },
  { id: "p8", name: "Custom Fields & Audit",  emoji: "🗃️", identifier: "AUD",  description: "JSONB custom fields per issue type + append-only audit log for compliance.",        status: "active",   progress: 55, ownerId: "u17", ownerName: "Fatima Al-Zahra", tenantId: "t3", issueCount: 3, startDate: "2025-04-05", targetDate: "2025-05-31", createdAt: "2025-04-03" },
  { id: "p9", name: "PDF Reporting Suite",    emoji: "📄", identifier: "PDF",  description: "Branded PDF exports for project status reports. Puppeteer-based generation.",       status: "planning", progress: 8,  ownerId: "u18", ownerName: "Jake Morrison",    tenantId: "t3", issueCount: 1, targetDate: "2025-07-15",                          createdAt: "2025-04-22" },
]
